北理珠/python/hengDaProject/hengDaProject/urls.py
from django.contrib import admin
from django.urls import path
from homeApp.views import home
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
import xadmin

urlpatterns = [
    path('admin/',xadmin.site.urls),
    path('', home, name='home'),
    path('aboutApp/', include('aboutApp.urls'), name='about'),
    path('contactApp/', include('contactApp.urls'), name='contact'),
    path('newsApp/', include('newsApp.urls'), name='news'),
    path('productsApp/', include('productsApp.urls'), name='products'),
    path('serviceApp/', include('serviceApp.urls'), name='service'),
    path('scienceApp/', include('scienceApp.urls'), name='science'),
    path('ueditor/',include('DjangoUeditor.urls')),
    path('search/',include('haystack.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

北理珠/python/hengDaProject/newsApp/urls.py
from django.urls import path
from . import views

app_name = 'newsApp'

urlpatterns = [
    path('news/<str:newName>/', views.news, name='news'),  # 企业要闻
    path('newDetail/<int:id>/', views.newDetail, name='newDetail'),
    path('search/', views.search, name='search')
]

北理珠/python/hengDaProject/newsApp/models.py
from DjangoUeditor.models import UEditorField
from django.db import models

# Create your models here.
from django.utils import timezone


class MyNew(models.Model):
    NEWS_CHOICES = (
        ('企业要闻','企业要闻'),
        ('行业新闻', '行业新闻'),
        ('通知公告', '通知公告'),
    )
    title = models.CharField(max_length=50,verbose_name='新闻标题')
    description = UEditorField(u'内容',default='',width=1000,height=300,imagePath='news/images/',filePath='news/files/')
    newType = models.CharField(choices=NEWS_CHOICES,max_length=50,verbose_name='新闻类型')
    publishDate = models.DateTimeField(max_length=20,default=timezone.now,verbose_name='发布时间')
    views = models.PositiveBigIntegerField('浏览量',default=0)
    photo = models.ImageField(upload_to='news/',blank=True,null=True,verbose_name='展报')
    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-publishDate']
        verbose_name = '新闻'
        verbose_name_plural = verbose_name

北理珠/python/hengDaProject/newsApp/views.py
from django.shortcuts import HttpResponse, render, get_object_or_404

from newsApp.models import MyNew
import productsApp.views
from pyquery import PyQuery as pq


def news(request, newName):
    submenu = newName
    newName = newName.replace('company', '企业要闻')
    newName = newName.replace('industry', '行业新闻')
    newName = newName.replace('notice', '通知公告')

    newList = MyNew.objects.all().filter(newType=newName).order_by('-publishDate')
    for mynew in newList:
        html = pq(mynew.description)
        mynew.mytxt = pq(html)('p').text()
    (pageData, newList) = productsApp.views.pageinator(newList, int(request.GET.get('page', 1)), size=5)
    return render(request, 'newList.html', {
        'active_menu': 'news',
        'sub_menu': submenu,
        'newName': newName,
        'newList': newList,
        'pageData': pageData,
    })


def newDetail(request, id):
    mynew = get_object_or_404(MyNew, id=id)
    mynew.views += 1
    mynew.save()
    return render(request, 'newDetail.html', {
        'active_menu': 'news',
        'mynew': mynew,
    })


def search(request):
    keyword = request.GET.get('keyword')
    newList = MyNew.objects.filter(title__icontains=keyword)
    newName = '关于“{}”的搜索结果'.format(keyword)
    return render(request, 'searchList.html', {
        'active_menu': 'news',
        'newName': newName,
        'newList': newList,
    })

北理珠/python/hengDaProject/newsApp/templates/newDetail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    新闻详情
{% endblock %}

{% block content %}
    <link href="{% static 'css/news.css' %}" rel="stylesheet">
    <!-- 主体内容 -->
    <div class="container">
        <div class="model-details-product-title">
            {{ mynew.title }}
            <div class="model-foot">
                发布时间:{{ mynew.publishDate | date:"Y-m-d" }} &nbsp; &nbsp;
                浏览次数：{{ mynew.views }}
            </div>
        </div>
        <div class="model-details">
            {{ mynew.description | safe }}
        </div>
    </div>
{% endblock %}

{% block script %}

{% endblock %}

北理珠/python/hengDaProject/newsApp/templates/newList.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    {{ newName }}
{% endblock %}

{% block content %}
    <link href="{% static 'css/news.css' %}" rel="stylesheet">
    <!-- 广告横幅 -->
    <div class="container-fluid">
        <div class="row">
            <img class="img-responsive model-img" src="{% static 'img/new.jpg' %}" alt="新闻动态">
        </div>
    </div>
    <div class="container">
        <div class="row row-3">
            <!-- 侧边导航栏 -->
            <div class="col-md-3">
                <div class="model-title">
                    新闻动态
                </div>
                <div class="model-list">
                    <ul class="list-group">
                        <li class="list-group-item" id="company">
                            <a href="{% url 'newsApp:news' 'company' %}">企业要闻</a>
                        </li>
                        <li class="list-group-item" id="industry">
                            <a href="{% url 'newsApp:news' 'industry' %}">行业新闻</a>
                        </li>
                        <li class="list-group-item" id="notice">
                            <a href="{% url 'newsApp:news' 'notice' %}">通知公告</a>
                        </li>
                    </ul>
                </div>
            </div>
            <!-- 说明文字和图片 -->
            <div class="col-md-9">
                <div class="model-details-title">
                    {{ newName }}
                    <div class="col-md-7 hidden-xs model-details-title-search">
                    <form method="get" action="{% url 'haystack_search' %}">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" name="q" class="form-control" placeholder="请输入关键词" required>
                            <span class="input-group-btn">
                                <input type="submit" class="btn btn-default" value="查询">
                            </span>
                        </div>
                    </form>
                </div>
                </div>
                <!-- 此处填入产品列表内容 -->
                <div class="model-details">
                    {% for mynew in newList %}
                        <div class="news-model">
                            <img src="{% static 'img/newsicon.gif' %}">
                            <a href="{% url 'newsApp:newDetail' mynew.id %}"><b>{{ mynew.title }}</b></a>
                            <span>【{{ mynew.publishDate | date:"Y-m-d" }}】</span>
                            <p>
                                <!-- 添加新闻简要说明 -->
                                {{ mynew.mytxt | truncatechars:"110" }}
                                ...
                            </p>
                        </div>
                    {% endfor %}

                    {% if pageData %}
                        <div class="paging">
                            <ul id="pages" class="pagination">
                                {% if pageData.first %}
                                    <li><a href="?page=1">1</a></li>
                                {% endif %}
                                {% if pageData.left %}
                                    {% if pageData.left_has_more %}
                                        <li><span>...</span></li>
                                    {% endif %}
                                    {% for i in pageData.left %}
                                        <li><a href="?page={{ i }}">{{ i }}</a></li>
                                    {% endfor %}
                                {% endif %}

                                <li class="active">
                                    <a href="?page={{ pageData.page }}">{{ pageData.page }}</a>
                                </li>

                                {% if pageData.right %}
                                    {% for i in pageData.right %}
                                        <li><a href="?page={{ i }}">{{ i }}</a></li>
                                    {% endfor %}
                                    {% if pageData.right_has_more %}
                                        <li><span>...</span></li>
                                    {% endif %}
                                {% endif %}
                                {% if pageData.last %}
                                    <li><a href="?page={{ pageData.total_pages }}">{{ pageData.total_pages }}</a></li>
                                {% endif %}
                            </ul>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}

{% endblock %}

北理珠/python/hengDaProject/newsApp/templates/searchList.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    {{ newName }}
{% endblock %}

{% block content %}
    <link href="{% static 'css/news.css' %}" rel="stylesheet">
    <!-- 广告横幅 -->
    <div class="container-fluid">
        <div class="row">
            <img class="img-responsive model-img" src="{% static 'img/new.jpg' %}" alt="新闻动态">
        </div>
    </div>
    <div class="container">
        <div class="row row-3">
            <!-- 说明文字和图片 -->
            <div class="model-details-title">
                {{ newName }}
                <div class="col-md-7 hidden-xs model-details-title-search">
                    <form method="get" action="{% url 'newsApp:search' %}">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" name="keyword" class="form-control" placeholder="请输入关键词" required>
                            <span class="input-group-btn">
                                <input type="submit" class="btn btn-default" value="查询">
                            </span>
                        </div>
                    </form>
                </div>
            </div>
            <!-- 此处填入产品列表内容 -->
            <div class="model-details">
                {% for mynew in newList %}
                    <div class="news-model">
                        <img src="{% static 'img/newsicon.gif' %}">
                        <a href="{% url 'newsApp:newDetail' mynew.id %}"><b>{{ mynew.title }}</b></a>
                        <span>【{{ mynew.publishDate | date:"Y-m-d" }}】</span>
                        <p>
                            <!-- 添加新闻简要说明 -->
                            {{ mynew.mytxt | truncatechars:"110" }}
                            ...
                        </p>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}

{% endblock %}