北理珠/python/hengDaProject/contactApp/urls.py
from django.urls import path
from . import views


app_name='contactApp'

urlpatterns=[
    path('contact/',views.contact,name='contact'), #欢迎咨询
    path('recruit/',views.recruit,name='recruit'), #加入恒达
]

北理珠/python/hengDaProject/hengDaProject/urls.py
from django.contrib import admin
from django.urls import path
from homeApp.views import home
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
import xadmin

urlpatterns = [
    path('admin/',xadmin.site.urls),
    path('', home, name='home'),
    path('aboutApp/', include('aboutApp.urls'), name='about'),
    path('contactApp/', include('contactApp.urls'), name='contact'),
    path('newsApp/', include('newsApp.urls'), name='news'),
    path('productsApp/', include('productsApp.urls'), name='products'),
    path('serviceApp/', include('serviceApp.urls'), name='service'),
    path('scienceApp/', include('scienceApp.urls'), name='science'),
    path('ueditor/',include('DjangoUeditor.urls')),
    path('search/',include('haystack.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

北理珠/python/hengDaProject/newsApp/urls.py
from django.urls import path
from . import views

app_name = 'newsApp'

urlpatterns = [
    path('news/<str:newName>/', views.news, name='news'),  # 企业要闻
    path('newDetail/<int:id>/', views.newDetail, name='newDetail'),
    path('search/', views.search, name='search')
]

北理珠/python/hengDaProject/contactApp/models.py
import os

from django.core.mail import send_mail
from django.db import models

# Create your models here.
from django.utils import timezone
from datetime import datetime
from django.db.models.signals import post_init, post_save
from django.dispatch import receiver
from docx.shared import Mm
from docxtpl import DocxTemplate, InlineImage


class Ad(models.Model):
    title = models.CharField(max_length=50, verbose_name='招聘岗位')
    description = models.TextField(verbose_name='岗位要求')
    publishDate = models.DateTimeField(max_length=20, default=timezone.now, verbose_name='发布时间')

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-publishDate']
        verbose_name = '招聘广告'
        verbose_name_plural = verbose_name


class Resume(models.Model):
    name = models.CharField(max_length=20, verbose_name='姓名')
    personID = models.CharField(max_length=30, verbose_name='身份证号')
    sex = models.CharField(max_length=5, default='男', verbose_name='性别')
    email = models.EmailField(max_length=30, verbose_name='邮箱')
    birth = models.DateField(max_length=20, default=datetime.strftime(datetime.now(), "%Y-%m-%d"), verbose_name='出生日期')
    edu = models.CharField(max_length=5, default='本科', verbose_name='学历')
    school = models.CharField(max_length=40, verbose_name='毕业院校')
    major = models.CharField(max_length=40, verbose_name='专业')
    position = models.CharField(max_length=40, verbose_name='申请职位')
    experience = models.TextField(blank=True, null=True, verbose_name='学习或工作经历')
    photo = models.ImageField(upload_to='contact/recruit/%Y_%m_%d', verbose_name='个人照片')
    grade_list = {
        (1, '未审'),
        (2, '通过'),
        (3, '未通过'),
    }
    status = models.IntegerField(choices=grade_list, default=1, verbose_name='面试成绩')
    publishDate = models.DateTimeField(max_length=20, default=timezone.now, verbose_name='提交时间')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '简历'
        verbose_name_plural = '简历'
        ordering = ('-status', '-publishDate')


@receiver(post_init, sender=Resume)
def before_save_resume(sender, instance, **kwargs):
    instance.__original_status = instance.status


@receiver(post_save, sender=Resume)
def post_save_resume(sender, instance, **kwargs):
    email = instance.email
    EMAIL_FROM = os.environ.get('EMAIL_HOST_USER')
    send_status = ""
    if instance.__original_status == 1 and instance.status == 2:
        email_title = '通知：恒达科技招聘初试结果'
        email_body = '恭喜您通过本企业初试'
        send_status = send_mail(email_title, email_body, EMAIL_FROM, [email])
    elif instance.__original_status == 1 and instance.status == 3:
        email_title = '通知：恒达科技招聘初试结果'
        email_body = '很遗憾，您未能通过本企业初试，感谢您的关注'
        send_status = send_mail(email_title, email_body, EMAIL_FROM, [email])
    print(instance.__original_status)
    print(instance.status)

    # 生成简历文档
    if instance.__original_status == 1 and instance.status == 2:
        template_path = os.getcwd() + '/media/recruit.docx'
        template = DocxTemplate(template_path)
        # 从instance实例中获取当前简历字段信息
        name = instance.name
        personID = instance.personID
        sex = instance.sex
        email = instance.email
        birth = instance.birth
        edu = instance.edu
        school = instance.school
        major = instance.major
        position = instance.position
        experience = instance.experience
        photo = instance.photo

        context = {
            'name': name,
            'personID': personID,
            'sex': sex,
            'email': email,
            'birth': birth,
            'edu': edu,
            'school': school,
            'major': major,
            'position': position,
            'experience': experience,
            'photo': InlineImage(template, photo, width=Mm(30), height=Mm(40)),
        }
        template.render(context)
        filename = '%s/media/contact/recruit/%s_%d.docx' % (os.getcwd(),instance.name,instance.id)
        template.save(filename)

北理珠/python/hengDaProject/contactApp/forms.py
from django import forms
from .models import Resume


class ResumeForm(forms.ModelForm):
    class Meta:
        model = Resume
        fields = (
        'name', 'sex', 'personID', 'email', 'birth', 'edu', 'school', 'major', 'experience', 'position', 'photo')
        sex_list = {
            ('男', '男'),
            ('女', '女'),
        }
        edu_list = {
            ('大专', '大专'),
            ('本科', '本科'),
            ('硕士', '硕士'),
            ('其他', '其他'),
        }
        widgets = {
            'sex':forms.Select(choices=sex_list),
            'edu': forms.Select(choices=edu_list),
            'photo': forms.FileInput(),
        }

北理珠/python/hengDaProject/contactApp/views.py
from django.shortcuts import HttpResponse, render

from contactApp.forms import ResumeForm
from contactApp.models import Ad


def contact(request):
    return render(request, 'contact.html', {
        'active_menu': 'employ',
        'sub_menu': 'contact'
    })


def recruit(request):
    AdList = Ad.objects.all().order_by('-publishDate')
    if request.method == 'POST':
        resumeForm = ResumeForm(data=request.POST, files=request.FILES)
        if resumeForm.is_valid():
            resumeForm.save()
            return render(request, 'success.html', {
                'active_menu': 'employ',
                'sub_menu': 'recruit',
            })
    else:
        resumeForm = ResumeForm()
        return render(request, 'recruit.html', {
            'active_menu': 'employ',
            'sub_menu': 'recruit',
            'AdList': AdList,
            'resumeForm': resumeForm,
        })

北理珠/python/hengDaProject/contactApp/templates/base_sidebar_contact.html
<!-- 侧边导航栏 -->
<div class="col-md-3">
    <div class="model-title">
        人才招聘
    </div>
    <div class="model-list">
        <ul class="list-group">
            <li class="list-group-item" id="contact">
                <a href="{% url 'contactApp:contact' %}">欢迎咨询</a>
            </li>
            <li class="list-group-item" id="recruit">
                <a href="{% url 'contactApp:recruit' %}">加入恒达</a>
            </li>
        </ul>
    </div>
</div>

北理珠/python/hengDaProject/contactApp/templates/contact.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    欢迎咨询
{% endblock %}
{% block content %}
    <link href="{% static 'css/contact.css' %}" rel="stylesheet">
    <!--引用百度地图样式-->
    <style type="text/css">
        .iw_poi_title {
            color: #CC5522;
            font-size: 14px;
            font-weight: bold;
            overflow: hidden;
            padding-right: 13px;
            white-space: nowrap
        }

        .iw_poi_content {
            font: 12px arial, sans-serif;
            overflow: visible;
            padding-top: 4px;
            white-space: -moz-pre-wrap;
            word-wrap: break-word
        }
    </style>
    <script type="text/JavaScript" src="http://api.map.baidu.com/api?key=&v=1.1&services=true">
    </script>
    <!-- 广告横幅 -->
    <div class="container-fluid">
        <div class="row">
            <img class="img-responsive model-img" src="{% static 'img/contact.jpg' %}" alt="人才招聘">
        </div>
    </div>
    <div class="container">
        <div class="row row-3">
            {% include "base_sidebar_contact.html" %}
            <div class="col-md-9">
                <div class="model-details-title">
                    欢迎咨询
                </div>
                <div class="col-md-4">
                    <div class="contact-left">
                        <h1>
                            <strong>恒达科技有限公司</strong>
                            <span>HengDa Science and Technology</span>
                        </h1>
                        <ul>
                            <li><span>业务质询一：</span>111-111111</li>
                            <li><span>业务质询二：</span>222-222222</li>
                            <li><span>咨询电话：</span>0111-1111111</li>
                            <li><span>企业传真：</span>0222-2222222</li>
                            <li><span>地址：</span>某某路某某大道某某号</li>
                            <li><span>邮编：</span>2222-222222</li>
                            <li><span>网址：</span>
                                <a href="http://python3web.com">http://python3web.com</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-8" style="margin-top: 20px;">
                    <div style="width:500px;height:400px;border:#ccc solid 1px;" id="dituContent"></div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        //创建和初始化地图函数：
        function initMap() {
            createMap();//创建地图
            setMapEvent();//设置地图事件
            addMapControl();//向地图添加控件
            addMarker();//向地图中添加marker
        }

        //创建地图函数：
        function createMap() {
            var map = new BMap.Map("dituContent");//在百度地图容器中创建一个地图
            var point = new BMap.Point(113.551461, 22.368546);//定义一个中心点坐标
            map.centerAndZoom(point, 15);//设定地图的中心点和坐标并将地图显示在地图容器中
            window.map = map;//将map变量存储在全局
        }

        //地图事件设置函数：
        function setMapEvent() {
            map.enableDragging();//启用地图拖拽事件，默认启用(可不写)
            map.enableScrollWheelZoom();//启用地图滚轮放大缩小
            map.enableDoubleClickZoom();//启用鼠标双击放大，默认启用(可不写)
            map.enableKeyboard();//启用键盘上下左右键移动地图
        }

        //地图控件添加函数：
        function addMapControl() {
            //向地图中添加缩放控件
            var ctrl_nav = new BMap.NavigationControl({
                anchor: BMAP_ANCHOR_TOP_LEFT,
                type: BMAP_NAVIGATION_CONTROL_LARGE
            });
            map.addControl(ctrl_nav);
            //向地图中添加缩略图控件
            var ctrl_ove = new BMap.OverviewMapControl({anchor: BMAP_ANCHOR_BOTTOM_RIGHT, isOpen: 1});
            map.addControl(ctrl_ove);
            //向地图中添加比例尺控件
            var ctrl_sca = new BMap.ScaleControl({anchor: BMAP_ANCHOR_BOTTOM_LEFT});
            map.addControl(ctrl_sca);
        }

        //标注点数组
        var markerArr = [{
            title: "恒达科技有限公司",
            content: "python web企业门户网站开发实战",
            //point: "121.507015|31.243978",
            point: "113.551461|22.368546",
            isOpen: 0,
            icon: {w: 21, h: 21, l: 0, t: 0, x: 6, lb: 5}
        }
        ];

        //创建marker
        function addMarker() {
            for (var i = 0; i < markerArr.length; i++) {
                var json = markerArr[i];
                var p0 = json.point.split("|")[0];
                var p1 = json.point.split("|")[1];
                var point = new BMap.Point(p0, p1);
                var iconImg = createIcon(json.icon);
                var marker = new BMap.Marker(point, {icon: iconImg});
                var iw = createInfoWindow(i);
                var label = new BMap.Label(json.title, {"offset": new BMap.Size(json.icon.lb - json.icon.x + 10, -20)});
                marker.setLabel(label);
                map.addOverlay(marker);
                label.setStyle({
                    borderColor: "#808080",
                    color: "#333",
                    cursor: "pointer"
                });

                (function () {
                    var index = i;
                    var _iw = createInfoWindow(i);
                    var _marker = marker;
                    _marker.addEventListener("click", function () {
                        this.openInfoWindow(_iw);
                    });
                    _iw.addEventListener("open", function () {
                        _marker.getLabel().hide();
                    })
                    _iw.addEventListener("close", function () {
                        _marker.getLabel().show();
                    })
                    label.addEventListener("click", function () {
                        _marker.openInfoWindow(_iw);
                    })
                    if (!!json.isOpen) {
                        label.hide();
                        _marker.openInfoWindow(_iw);
                    }
                })()
            }
        }

        //创建InfoWindow
        function createInfoWindow(i) {
            var json = markerArr[i];
            var iw = new BMap.InfoWindow("<b class='iw_poi_title' title='" + json.title + "'>" + json.title + "</b><div class='iw_poi_content'>" + json.content + "</div>");
            return iw;
        }

        //创建一个Icon
        function createIcon(json) {
            var icon = new BMap.Icon("http://map.baidu.com/image/us_mk_icon.png", new BMap.Size(json.w, json.h), {
                imageOffset: new BMap.Size(-json.l, -json.t),
                infoWindowOffset: new BMap.Size(json.lb + 5, 1),
                offset: new BMap.Size(json.x, json.h)
            })
            return icon;
        }

        initMap();//创建和初始化地图
    </script>
{% endblock %}
{% block script %}

{% endblock %}

北理珠/python/hengDaProject/contactApp/templates/recruit.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block title %}
    加入恒达
{% endblock %}
{% block content %}
    <link href="{% static 'css/contact.css' %}" rel="stylesheet">
    <script src="{% static 'js/laydate/laydate.js' %}"></script>

    <div class="container">
    <div class="row row-3">
        {% include "base_sidebar_contact.html" %}
        <div class="col-md-9">
            <div class="model-details-title">
                加入恒达
            </div>

            <div class="model-details">
                <div class="panel-group" id="accordion">
                    {% for ad in AdList %}
                        <div class="panel panel-default">
                        <div class="panel-heading" role="tab" id="panel{{ ad.id }}">
                            <h4 class="panel-title">
                                {% if forloop.first %}
                                    <a role="button" data-toggle="collapse" data-parent="#accordion"
                                       href="#collapse{{ ad.id }}">
                                {% else %}
                                    <a class="collapsed" data-toggle="collapse" data-parent="#accordion"
                                       href="#collapse{{ ad.id }}">
                                {% endif %}
                                {{ ad.title }}
                                </a>
                            </h4>
                        </div>
                        {% if forloop.first %}
                            <div id="collapse{{ ad.id }}" class="panel-collapse collapse in">
                        {% else %}
                            <div id="collapse{{ ad.id }}" class="panel-collapse collapse">
                        {% endif %}
                    <div class="panel-body">
                        <p>{{ ad.description }}</p>
                    </div>
                    </div>
                    </div>
                    {% endfor %}


                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        请填写个人简历
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <form action="." name="resumeForm" method="post" class="form-horizontal" role="form"
                                  enctype="multipart/form-data">
                                {% csrf_token %}
                                <!-- 左侧 -->
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="col-sm-3 control-label">姓名：</label>
                                        <div class="col-sm-9">
                                            {{ resumeForm.name | add_class:"form-control" | attr:"placeholder=请填写姓名" }}
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-3 control-label">身份证号：</label>
                                        <div class="col-sm-9">
                                            {{ resumeForm.personID | add_class:"form-control" }}
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-3 control-label">性别：</label>
                                        <div class="col-sm-9">
                                            {{ resumeForm.sex | add_class:"form-control" }}
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-3 control-label">出生日期：</label>
                                        <div class="col-sm-9">
                                            {{ resumeForm.birth | add_class:"form-control" }}
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-3 control-label">邮箱：</label>
                                        <div class="col-sm-9">
                                            {{ resumeForm.email | add_class:"form-control" }}
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-3 control-label">学历：</label>
                                        <div class="col-sm-9">
                                            {{ resumeForm.edu | add_class:"form-control" }}
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-3 control-label">毕业学校：</label>
                                        <div class="col-sm-9">
                                            {{ resumeForm.school | add_class:"form-control" }}
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-3 control-label">专业：</label>
                                        <div class="col-sm-9">
                                            {{ resumeForm.major | add_class:"form-control" }}
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-3 control-label">申请职位：</label>
                                        <div class="col-sm-9">
                                            {{ resumeForm.position | add_class:"form-control" }}
                                        </div>
                                    </div>
                                </div>
                                <!-- 右侧 -->
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <div class="col-sm-12" style="text-align:center">
                                            <img id="profileshow" src="{% static 'img/sample.png' %}"
                                                 style="width:120px">
                                        </div>
                                        <label class="col-sm-5 control-label">上传证件照片：</label>
                                        {{ resumeForm.photo }}
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-12 control-label">学习或工作经历：</label>
                                        <div class="col-sm-12">
                                            {{ resumeForm.experience | add_class:"form-control" }}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <center><input type="submit" class="btn btn-primary" value="提交"></center>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script>
        laydate.render({
            elem: "#id_birth"
        })
    </script>
    <script>
        $(function () {
            $('#id_photo').on('change', function () {   <!--id号为id_photo发生改变-->
                var r = new FileReader();
                f = document.getElementById('id_photo').files[0];
                r.readAsDataURL(f);
                r.onload = function (e) {
                    document.getElementById('profileshow').src = this.result;  <!--profileshow为上方img元素的id号-->
                };
            });
        });
    </script>
{% endblock %}

北理珠/python/hengDaProject/contactApp/templates/success.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    人才招聘
{% endblock %}

{% block content %}
<!-- 主体内容 -->
<div class="container">
    <div class="row">
        <div class="alert alert-success">
            <strong>成功!</strong> 简历信息已成功上传，初试结果近期会以邮件方式发送至您的邮箱。
        </div>
    </div>
</div>
{% endblock %}